export interface MockTicket {
  id: string;
  eventId: string;
  eventName: string;
  date: string;
  dateDisplay?: string;
  time: string;
  venue?: string;
  location: string;
  seat: string;
  quantity?: number;
  price: number;
  status: 'active' | 'used' | 'cancelled';
}

export const mockTickets: MockTicket[] = [
  {
    id: 'ticket-1',
    eventId: '1',
    eventName: 'SANTALAND 2025',
    date: '2025-12-12',
    dateDisplay: '12 dic 2025',
    time: '18:00',
    venue: 'Centro de Convenciones',
    location: 'Barranquilla',
    seat: 'Sección A, Fila 5, Asiento 12',
    quantity: 2,
    price: 85000,
    status: 'active',
  },
  {
    id: 'ticket-2',
    eventId: '2',
    eventName: 'FESTIVAL NACIONAL DE COMPOSITORES 2025',
    date: '2025-12-12',
    dateDisplay: '12 dic 2025',
    time: '19:00',
    venue: 'Plaza Principal',
    location: 'San Juan del Cesar, La Guajira',
    seat: 'General',
    quantity: 1,
    price: 120000,
    status: 'active',
  },
  {
    id: 'ticket-3',
    eventId: '3',
    eventName: 'QUIÉN SE LLEVÓ LA NAVIDAD?',
    date: '2025-11-29',
    dateDisplay: '29 nov 2025',
    time: '20:00',
    venue: 'Teatro Amira de la Rosa',
    location: 'Barranquilla',
    seat: 'Platea, Fila 8, Asiento 15-16',
    quantity: 2,
    price: 75000,
    status: 'active',
  },
  {
    id: 'ticket-4',
    eventId: '4',
    eventName: 'CONCIERTO DE ROCK NACIONAL',
    date: '2025-12-20',
    dateDisplay: '20 dic 2025',
    time: '20:00',
    venue: 'Coliseo El Campín',
    location: 'Bogotá',
    seat: 'VIP, Fila 1, Asiento 5',
    quantity: 1,
    price: 95000,
    status: 'active',
  },
  {
    id: 'ticket-5',
    eventId: '5',
    eventName: 'FESTIVAL DE ARTE URBANO',
    date: '2025-12-15',
    dateDisplay: '15 dic 2025',
    time: '14:00',
    venue: 'Parque Lleras',
    location: 'Medellín',
    seat: 'General',
    quantity: 3,
    price: 65000,
    status: 'active',
  },
  {
    id: 'ticket-6',
    eventId: '6',
    eventName: 'MARATÓN DE LA CIUDAD',
    date: '2025-12-10',
    dateDisplay: '10 dic 2025',
    time: '06:00',
    venue: 'Punto de Salida',
    location: 'Cali',
    seat: 'Categoría 10K',
    quantity: 1,
    price: 50000,
    status: 'active',
  },
  {
    id: 'ticket-7',
    eventId: '1',
    eventName: 'SANTALAND 2025',
    date: '2025-12-13',
    dateDisplay: '13 dic 2025',
    time: '18:00',
    venue: 'Centro de Convenciones',
    location: 'Barranquilla',
    seat: 'Sección B, Fila 10, Asiento 20',
    quantity: 1,
    price: 85000,
    status: 'active',
  },
  {
    id: 'ticket-8',
    eventId: '1',
    eventName: 'SANTALAND 2025',
    date: '2025-12-14',
    dateDisplay: '14 dic 2025',
    time: '18:00',
    venue: 'Centro de Convenciones',
    location: 'Barranquilla',
    seat: 'Sección VIP, Fila 2, Asiento 8-9',
    quantity: 2,
    price: 120000,
    status: 'active',
  },
  {
    id: 'ticket-9',
    eventId: '4',
    eventName: 'CONCIERTO DE ROCK NACIONAL',
    date: '2025-12-20',
    dateDisplay: '20 dic 2025',
    time: '20:00',
    venue: 'Coliseo El Campín',
    location: 'Bogotá',
    seat: 'Pista, Zona A',
    quantity: 2,
    price: 150000,
    status: 'active',
  },
  {
    id: 'ticket-10',
    eventId: '5',
    eventName: 'FESTIVAL DE ARTE URBANO',
    date: '2025-12-15',
    dateDisplay: '15 dic 2025',
    time: '14:00',
    venue: 'Parque Lleras',
    location: 'Medellín',
    seat: 'Zona Premium',
    quantity: 4,
    price: 80000,
    status: 'active',
  },
  {
    id: 'ticket-11',
    eventId: '2',
    eventName: 'FESTIVAL NACIONAL DE COMPOSITORES 2025',
    date: '2025-12-13',
    dateDisplay: '13 dic 2025',
    time: '19:00',
    venue: 'Plaza Principal',
    location: 'San Juan del Cesar, La Guajira',
    seat: 'VIP, Primera Fila',
    quantity: 1,
    price: 180000,
    status: 'active',
  },
  {
    id: 'ticket-12',
    eventId: '3',
    eventName: 'QUIÉN SE LLEVÓ LA NAVIDAD?',
    date: '2025-11-30',
    dateDisplay: '30 nov 2025',
    time: '20:00',
    venue: 'Teatro Amira de la Rosa',
    location: 'Barranquilla',
    seat: 'Balcón, Fila 3, Asiento 10',
    quantity: 1,
    price: 75000,
    status: 'active',
  },
  {
    id: 'ticket-13',
    eventId: '6',
    eventName: 'MARATÓN DE LA CIUDAD',
    date: '2025-12-10',
    dateDisplay: '10 dic 2025',
    time: '06:00',
    venue: 'Punto de Salida',
    location: 'Cali',
    seat: 'Categoría 21K',
    quantity: 1,
    price: 75000,
    status: 'active',
  },
  {
    id: 'ticket-14',
    eventId: '1',
    eventName: 'SANTALAND 2025',
    date: '2025-12-12',
    dateDisplay: '12 dic 2025',
    time: '18:00',
    venue: 'Centro de Convenciones',
    location: 'Barranquilla',
    seat: 'Sección C, Fila 15, Asiento 25-27',
    quantity: 3,
    price: 85000,
    status: 'active',
  },
  {
    id: 'ticket-15',
    eventId: '4',
    eventName: 'CONCIERTO DE ROCK NACIONAL',
    date: '2025-12-21',
    dateDisplay: '21 dic 2025',
    time: '20:00',
    venue: 'Coliseo El Campín',
    location: 'Bogotá',
    seat: 'Tribuna, Fila 5, Asiento 12',
    quantity: 1,
    price: 95000,
    status: 'active',
  },
  {
    id: 'ticket-16',
    eventId: '5',
    eventName: 'FESTIVAL DE ARTE URBANO',
    date: '2025-12-16',
    dateDisplay: '16 dic 2025',
    time: '14:00',
    venue: 'Parque Lleras',
    location: 'Medellín',
    seat: 'General',
    quantity: 2,
    price: 65000,
    status: 'active',
  },
  {
    id: 'ticket-17',
    eventId: '2',
    eventName: 'FESTIVAL NACIONAL DE COMPOSITORES 2025',
    date: '2025-12-14',
    dateDisplay: '14 dic 2025',
    time: '19:00',
    venue: 'Plaza Principal',
    location: 'San Juan del Cesar, La Guajira',
    seat: 'General',
    quantity: 2,
    price: 120000,
    status: 'active',
  },
  {
    id: 'ticket-18',
    eventId: '6',
    eventName: 'MARATÓN DE LA CIUDAD',
    date: '2025-12-10',
    dateDisplay: '10 dic 2025',
    time: '06:00',
    venue: 'Punto de Salida',
    location: 'Cali',
    seat: 'Categoría 5K',
    quantity: 2,
    price: 35000,
    status: 'active',
  },
  {
    id: 'ticket-19',
    eventId: '3',
    eventName: 'QUIÉN SE LLEVÓ LA NAVIDAD?',
    date: '2025-12-01',
    dateDisplay: '1 dic 2025',
    time: '20:00',
    venue: 'Teatro Amira de la Rosa',
    location: 'Barranquilla',
    seat: 'Platea, Fila 12, Asiento 30-31',
    quantity: 2,
    price: 75000,
    status: 'active',
  },
  {
    id: 'ticket-20',
    eventId: '1',
    eventName: 'SANTALAND 2025',
    date: '2025-12-12',
    dateDisplay: '12 dic 2025',
    time: '18:00',
    venue: 'Centro de Convenciones',
    location: 'Barranquilla',
    seat: 'Sección Premium, Fila 1, Asiento 3-6',
    quantity: 4,
    price: 120000,
    status: 'active',
  },
];

